"""Constants for integration_blueprint tests."""
from homeassistant.const import CONF_NAME

from custom_components.replacements.const import (
    DOMAIN,
    CONF_DAYS_INTERVAL,
    CONF_WEEKS_INTERVAL,
    CONF_SOON,
    CONF_PREFIX,
    CONF_UNIT_OF_MEASUREMENT,
    CONF_ICON_EXPIRED,
    CONF_ICON_NORMAL,
    CONF_ICON_SOON,
    CONF_ICON_TODAY,
    DEFAULT_SOON,
    DEFAULT_PREFIX,
    DEFAULT_UNIT_OF_MEASUREMENT,
    DEFAULT_ICON_NORMAL,
    DEFAULT_ICON_SOON,
    DEFAULT_ICON_TODAY,
    DEFAULT_ICON_EXPIRED,
    CONF_ADD_ANOTHER,
    GROUP_INTERVAL,
    CONF_INTERVAL_EXCLUSION_ERROR,
)

# Mock config data to be used across multiple tests
MOCK_CONFIG_DAYS_ANOTHER = {
    CONF_NAME: "Test Days 1",
    CONF_PREFIX: DEFAULT_PREFIX,
    CONF_DAYS_INTERVAL: 5,
    CONF_SOON: DEFAULT_SOON,
    CONF_UNIT_OF_MEASUREMENT: DEFAULT_UNIT_OF_MEASUREMENT,
    CONF_ICON_NORMAL: DEFAULT_ICON_NORMAL,
    CONF_ICON_SOON: DEFAULT_ICON_SOON,
    CONF_ICON_TODAY: DEFAULT_ICON_TODAY,
    CONF_ICON_EXPIRED: DEFAULT_ICON_EXPIRED,
    CONF_ADD_ANOTHER: True,
}

MOCK_CONFIG_WEEKS = {
    CONF_NAME: "Test Weeks 2",
    CONF_PREFIX: DEFAULT_PREFIX,
    CONF_DAYS_INTERVAL: 5,
    CONF_SOON: DEFAULT_SOON,
    CONF_UNIT_OF_MEASUREMENT: DEFAULT_UNIT_OF_MEASUREMENT,
    CONF_ICON_NORMAL: DEFAULT_ICON_NORMAL,
    CONF_ICON_SOON: DEFAULT_ICON_SOON,
    CONF_ICON_TODAY: DEFAULT_ICON_TODAY,
    CONF_ICON_EXPIRED: DEFAULT_ICON_EXPIRED,
    CONF_ADD_ANOTHER: False,
}
