"""Constants for integration_blueprint tests."""
from homeassistant.const import CONF_NAME

from custom_components.replacements.const import (
    CONF_ADD_ANOTHER,
    CONF_DAYS_INTERVAL,
    CONF_ICON_EXPIRED,
    CONF_ICON_NORMAL,
    CONF_ICON_SOON,
    CONF_ICON_TODAY,
    CONF_PREFIX,
    CONF_SOON,
    CONF_UNIT_OF_MEASUREMENT,
    CONF_WEEKS_INTERVAL,
    DEFAULT_ICON_EXPIRED,
    DEFAULT_ICON_NORMAL,
    DEFAULT_ICON_SOON,
    DEFAULT_ICON_TODAY,
    DEFAULT_PREFIX,
    DEFAULT_SOON,
    DEFAULT_UNIT_OF_MEASUREMENT,
)

# Mock config data to be used across multiple tests
MOCK_CONFIG_DAYS = {
    CONF_NAME: "Test Days 1",
    CONF_PREFIX: DEFAULT_PREFIX,
    CONF_DAYS_INTERVAL: 4,
    CONF_SOON: DEFAULT_SOON,
    CONF_UNIT_OF_MEASUREMENT: DEFAULT_UNIT_OF_MEASUREMENT,
    CONF_ICON_NORMAL: DEFAULT_ICON_NORMAL,
    CONF_ICON_SOON: DEFAULT_ICON_SOON,
    CONF_ICON_TODAY: DEFAULT_ICON_TODAY,
    CONF_ICON_EXPIRED: DEFAULT_ICON_EXPIRED,
    CONF_ADD_ANOTHER: True,
}

MOCK_CONFIG_WEEKS = {
    CONF_NAME: "Test Weeks 2",
    CONF_PREFIX: DEFAULT_PREFIX,
    CONF_WEEKS_INTERVAL: 6,
    CONF_SOON: 3,
    CONF_UNIT_OF_MEASUREMENT: "Weeks",
    CONF_ICON_NORMAL: DEFAULT_ICON_NORMAL,
    CONF_ICON_SOON: DEFAULT_ICON_SOON,
    CONF_ICON_TODAY: DEFAULT_ICON_TODAY,
    CONF_ICON_EXPIRED: DEFAULT_ICON_EXPIRED,
    CONF_ADD_ANOTHER: False,
}

MOCK_CONFIG_ADDITIONAL = {
    CONF_NAME: "Test Weeks 3",
    CONF_PREFIX: DEFAULT_PREFIX,
    CONF_WEEKS_INTERVAL: 10,
    CONF_SOON: DEFAULT_SOON,
    CONF_UNIT_OF_MEASUREMENT: "Weeks",
    CONF_ICON_NORMAL: DEFAULT_ICON_NORMAL,
    CONF_ICON_SOON: DEFAULT_ICON_SOON,
    CONF_ICON_TODAY: DEFAULT_ICON_TODAY,
    CONF_ICON_EXPIRED: DEFAULT_ICON_EXPIRED,
    CONF_ADD_ANOTHER: False,
}

MOCK_CONFIG_ERROR = {
    CONF_NAME: "Test Weeks 3",
    CONF_PREFIX: DEFAULT_PREFIX,
    CONF_WEEKS_INTERVAL: 4,
    CONF_SOON: 6,
    CONF_UNIT_OF_MEASUREMENT: "Weeks",
    CONF_ICON_NORMAL: DEFAULT_ICON_NORMAL,
    CONF_ICON_SOON: DEFAULT_ICON_SOON,
    CONF_ICON_TODAY: DEFAULT_ICON_TODAY,
    CONF_ICON_EXPIRED: DEFAULT_ICON_EXPIRED,
    CONF_ADD_ANOTHER: False,
}


MOCK_CONFIG_SMALL = {
    CONF_NAME: "Test Small",
    CONF_DAYS_INTERVAL: 5,
    CONF_SOON: DEFAULT_SOON,
}
