name: Release

on:
  release:
    types: [published]

jobs:
  release:
    name: Prepare release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Get version
        id: version
        uses: home-assistant/actions/helpers/version@master

      - name: "Set version number"
        run: |
          sed -i '/VERSION = /c\VERSION = "${{ steps.version.outputs.version }}"' custom_components/replacements/const.py
          sed -i 's|"version": "1.0.0"|"version": "${{ steps.version.outputs.version }}"|' custom_components/replacements/manifest.json

      # Pack the HACS dir as a zip and upload to the release
      - name: ZIP replacements Dir
        run: |
          cd ${{ github.workspace }}/custom_components/replacements
          zip replacements.zip -r ./

      - name: Upload zip to release
        uses: svenstaro/upload-release-action@v1-release

        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ github.workspace }}/custom_components/replacements/replacements.zip
          asset_name: replacements.zip
          tag: ${{ github.ref }}
          overwrite: true
